name: Keepcraft
main: keepcraft.Keepcraft
version: 2
commands:
    g:
        description: Send global message to server
        usage: /g <message>
    who: 
        description: Get user info
        usage: /who <username>
    map:
        description: Outpost commands
        usage: /map
    rally:
        description: Alias for /map
        usage: /rally
    global:
        description: Toggle global chat
        usage: /global on|off
    die:
        description: Suicide
        usage: /die
    promote:
        description: Promote privilege
        usage: /promote <username>
    demote:
        description: Demote privilege
        usage: /demote <user name>
    delete:
        description: Delete a user record
        usage: /delete <user name>
    faction:
        description: Set faction properties
        usage: /faction <#> etc.
    setteam:
        description: Change a user's team
        usage: /setteam <username> <#>
    ptp:
        description: Teleport to a plot by name
        usage: /ptp <plot name>
    chest:
        description: Edit a chest
        usage: /chest
    dawn:
        description: Let there be light!
        usage: /dawn
    noon:
        description: Make it noon
        usage: /noon
    dusk:
        description: Make it dusk
        usage: /dusk
    1:
        description: Chat in Red's team channel
        usage: /1 <message>
    2:
        description: Chat in Blue's team channel
        usage: /2 <message>
    3:
        description: Chat in Greens team channel
        usage: /3 <message>
    plot:
        description: Plot commands
        usage: /plot
    join:
        description: Join a player's team
        usage: /join <name>
    cap:
        description: Begin capturing a plot
        usage: /cap
    capture:
        description: Begin capturing a plot
        usage: /capture
    approve:
        description: Approve a graylisted user on your team
        usage: /approve <name>
        